name: PDF to HTML

on:
  push:
    paths:
      - '*.pdf'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pymupdf

    - name: Convert PDF to HTML
      run: |
        python process_pdf.py
      continue-on-error: true

    - name: Print logs
      if: failure()
      run: |
        cat /home/runner/work/_temp/_runner_file_commands/echo.txt
